# to publish
# update the CHANGELOG.md
# updated the pubspec.yaml file version
# Run:
#  `dart pub publish`


name: simple_deploy
description: A quick and easy way to push deployment to Test Flight and the play store internal test track
version: 0.11.0
homepage: https://github.com/andrewpmoore/simple_deploy


environment:
  sdk: ^3.5.4

dependencies:
  # path: ^1.8.0
  googleapis_auth: ^1.6.0  #handle the auth
  googleapis: ^13.2.0  #play store api access
  http: ^1.2.2  #connection to play store api
  yaml: ^3.1.0  #load the yaml file

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
